### ISSUE TITLE
default curtain and speech bubble speeds

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1159]
curently the default speeds for fading of speech bubbles and curtain movement are set to the fastest possible. 
could the default please be in the middle of the slider?
(very non-urgent issue)

**Comment by helenvarley** [comment]
also, i'm not sure if the speech bubble fade speed makes any difference. the curtain lowered a bit faster or slower depending on where the slider was set, but i honestly couldn't tell for the speech bubbles - seemed to fade just as fast no matter where the slider was.

**Comment by gloriajw** [comment]
Fixed, pls test:

Default speeds set to middle of slider
Customisation.vue
Speech bubble speed: default bubbleSpeed changed from 1000 to 2000 ms.
Slider is value = 1000 / bubbleSpeed with range 0.1–1, so 2000 ms corresponds to 0.5 (middle).
Curtain speed: default curtainSpeed changed from 5000 to 10000 ms.
Slider is value = 5000 / curtainSpeed with range 0.1–1, so 10000 ms corresponds to 0.5 (middle).
Defaults are used in:
getDefaultConfig()
Initial animations when loading config
Save payload fallbacks (Number(...) || 2000 / || 10000)
Curtain.vue
Fallback when no config is present updated from 3000 to 10000 ms so it matches the new default.
Topping.vue
Fallback for missing bubbleSpeed updated from 1000 to 2000 ms.
2. Speech bubble fade speed
The speech bubble does use bubbleSpeed:
Topping.vue uses config.value?.animations?.bubbleSpeed for both:
enter: fade-in (opacity 0 → 1) or bounce-in
leave: fade-out (opacity → 0) or bounce-out
with duration passed into the animejs animate() calls.
So the slider controls both the appear and disappear animation length. A debug console.log in the enter handler was removed.
If you still don’t see a difference after moving the slider and saving:
Reload the stage tab (or re-enter the stage). Customisation is loaded when the stage is loaded; changing and saving in Studio doesn’t push config into an already-open stage view, so the live view can still be using the old config until it’s reloaded.
Watch the disappear. The bubble stays for 5 seconds (BUBBLE_TIMEOUT), then the leave transition runs. With a slow setting (e.g. 10 s), the fade-out should be clearly longer than at 1–2 s.
If you want the bubble to stay on screen longer so the fade is easier to compare, we can increase BUBBLE_TIMEOUT or make it configurable next.

**Comment by helenvarley** [comment]
i can't test this right now because all stages are offline ...

**Comment by helenvarley** [comment]
as far as i can tell this is not fixed on dev.upstage.live - when i create a new stage, the speed of speech bubble and curtain are both showing as fast as possible. they should be set to the middle as default (this is not super urgent but hopefully something easy to fix?)

<img width="1641" height="658" alt="Image" src="https://github.com/user-attachments/assets/f0e3be58-b76b-411a-a42e-110520591128" />

**Comment by gloriajw** [comment]
should be fixed, pls test.

**Comment by helenvarley** [comment]
great, fixed 👍
