### ISSUE TITLE
Admin cannot manage or delete others' media that is set to "not shared"

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1219]
if a player has set the permissions on a media item to "not shared", it is no longer possible for an Admin to manage or delete that media. normally this isn't a problem, but there could be situations where a player has uploaded a corrupt file or for some other reason an Admin needs to help them with the media or delete it.
Is it possible for Admins to still have manage and delete powers even when a media item is set to "not shared"?

**Comment by helenvarley** [comment]
this is the same as #892

**Comment by webdev604** [comment]
![image](https://github.com/upstage-org/upstage/assets/35217708/75d46945-fbe8-4c40-b47e-32c341e570c1)
hi @helenvarley 
I think it was already fixed. can you check again? attached screenshot

**Comment by helenvarley** [comment]
no, it's not fixed. maybe i wasn't clear - i meant that an Admin should be able to edit media belonging to another player, that has been set to not shared.
![Screenshot from 2024-03-07 10:43:14](https://github.com/upstage-org/upstage/assets/3437324/ed3be459-ae4f-42a5-a02d-a0048f06c9ec)

**Comment by helenvarley** [comment]
tested and now working: Admins (& Super Admins) can edit others' media even when set to "not shared" :+1:
