### ISSUE TITLE
"Customise Foyer" button on Foyer doesn't work

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1268]
this is what i get when i click on the "Customise Foyer" button on the Foyer of upstage.live:

![Screenshot from 2024-05-12 14:57:29](https://github.com/upstage-org/upstage/assets/3437324/532c2398-b773-4f49-a001-2250b2393b2c)

**Comment by webdev604** [comment]
hi @helenvarley 
please retry. it should work now

**Comment by helenvarley** [comment]
it's working on upstage.live, but i changed it in the Foyer customisation settings. i tried now on dev-app & still get the url with legacy/backstage in it; so the default url in the code is still wrong.

& this shouldn't be something that can be changed in the Customise Foyer settings.

**Comment by webdev604** [comment]
hi @helenvarley 
I could change in settings and it worked for me
![image](https://github.com/upstage-org/upstage/assets/35217708/1d4f5ccd-70bc-4aa2-a2e8-9bbb54c58c12)

**Comment by helenvarley** [comment]
yes, i can also do this. but the point is that in a new install, it will still have the legacy/backstage url as a default. 
a new install should have the correct link to start with (& there's not really any need for it to be editable ... )

**Comment by webdev604** [comment]
I think it would never happen again because we already have updated the field in both dev and live

**Comment by helenvarley** [comment]
has dev-app been updated with this? i am still getting a blank page on dev-app, when i use the "customise foyer" button on the foyer to try to reach that interface.
if i navigate there from the Studio, it works, and the url is https://dev-app1.upstage.live/admin/configuration. i can see there that the link for the "Customise Foyer" button is /admin/foyer-customisation, but if i go back to the Foyer and click on the button, it brings me to https://dev-app1.upstage.live/admin/foyer-customisation and a blank page ...

**Comment by webdev604** [comment]
hi @helenvarley I couldn't reproduce. once I update with new url, I can't see old url anymore.

**Comment by helenvarley** [comment]
great, thanks. as long as the correct url is what appears as the default in a new installation, then it should be fine :+1:
