### ISSUE TITLE
Testing dev-app2 - foyer customisation toggles

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1363]
in the Foyer Customisation interface, we can chose to display or hide the registration button and the donation bar. in the current version, these are toggles:

![Image](https://github.com/user-attachments/assets/47bc8f89-b67a-417b-a4a8-4072054c9fdf)

but on dev-app2, they are showing as editable fields with true. it would be more user-friendly to have toggles as before

![Image](https://github.com/user-attachments/assets/4f371080-aacf-482b-ad65-5352cc43d673)

**Comment by webdev604** [comment]
fixed. please test

**Comment by helenvarley** [comment]
great - the donate toggle works but the registration one doesn't - i turned it off then logged out, and still saw the registration button on the Foyer.

**Comment by helenvarley** [comment]
this is still not fixed, & is quite important as there can be many situations where the registration link needs to be hidden.

**Comment by nnguyenquangg** [comment]
it's fixed @helenvarley

**Comment by helenvarley** [comment]
i'm still seeing the registration button on the foyer, after i've turned off the toggle ...

**Comment by nnguyenquangg** [comment]
it's fixed @helenvarley

**Comment by helenvarley** [comment]
great! 👍
