### ISSUE TITLE
avatar on stage after being unassigned

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1448]
on the Demo stage on dev.upstage.org, the penguin avatar was on the stage when i entered. however it is not shown in the avatar tool bar on that stage, & when i checked in the studio, it is not assigned to the Demo stage. presumably it was (it's one of the default media that should be on the Demo stage in a new install) & then has been unassigned - but it is still showing on the stage.

if a media item is unassigned from a stage, it should not show there, even if it was placed on the stage while assigned and not removed before being unassigned.

<img width="759" height="553" alt="Image" src="https://github.com/user-attachments/assets/78ed30ab-141c-446c-adf2-d0127d4b6c3e" />

<img width="800" height="332" alt="Image" src="https://github.com/user-attachments/assets/83b67777-e27d-402a-a649-a974e79ff2cd" />

**Comment by helenvarley** [comment]
note: i've archived the stage so it's been swept, & now the avatar is not there. however, it's been saved in scenes & if i select one of the scenes, it does appear.
i know this happens for text and drawing - it can be saved in a scene & will be there when you return to the stage, which is a useful thing. but if a media item has been unassigned from a stage, i don't think it should show up in scenes. 
@vickis any thoughts on that?

**Comment by helenvarley** [comment]
(another note: this is not such a terrible thing that it should stop the roll-out of the code on dev to upstage.live)

**Comment by gloriajw** [comment]
Fixed, please test. Rollback patch attached. 

[unassigned_media.patch](https://github.com/user-attachments/files/24915313/unassigned_media.patch)

**Comment by vickis** [comment]
Media item remains - this is a complication (it is the connection to scenes, like drawing or text)

**Comment by helenvarley** [comment]
vicki & i have discussed & agreed that, if a media item has been saved in a scene then unassigned from that stage, it should still appear in the scene, but not in the toolbars. this is how it's working now, so i'll close the issue.
(it's a little bit confusing when you know you've unassigned something that you then see on the stage, but i don't think it's going to be a problem)
