### ISSUE TITLE
drawing - browser issue

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1450]
using the Brave browser: if i select a colour and draw something, then select a different colour and start to draw again, the previous line will be changed to the new colour.

if i don't want this to happen, i have to first click away from the colour selector palette, on the toolbar, not on the stage. so this is a work around, but it's not intuitive.

this is definitely a browser issue, as in Firefox the colour palette has a "Select" button. i haven't tried other browsers, but wondering if it's possible for there to always be a "select" button, regardless of the browser being used? or is this not possible?

![Image](https://github.com/user-attachments/assets/96e05ecf-771d-419d-9bb7-74bbd9a5ee5c)

firefox palette:

<img width="645" height="560" alt="Image" src="https://github.com/user-attachments/assets/2618047d-c697-4c3e-8894-62b0d243922e" />

**Comment by helenvarley** [comment]
(note: this is not such a terrible thing that it should stop the roll-out of the code on dev to upstage.live)

**Comment by gloriajw** [comment]
Fixed, please test. It should work on all browsers. Not sure if you will see a select button where you did not see it before, but it should work intuitively.

**Comment by vickis** [comment]
this is a browser issue - not happening for me

**Comment by helenvarley** [comment]
it's still happening for me, using Brave; but i will not worry about it - if i need to do drawing (rare!) i'll use another browser.

**Comment by gloriajw** [comment]
I finally frigging found the cause of this. The brave color picker sends an unexpected event causing a duplicate draw event. It is fixed now. Whew, that took a long time, even for AI.

**Comment by helenvarley** [comment]
yay! thanks for your persistence 🙏 it's now working as expected in brave.
